name: Build WebGL, Windows, Linux

"on":
  push:
    branches:
      - main

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
  buildTargetPlatforms:
    name: Build for ${{ matrix.targetPlatform.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - name: Windows
            platform: StandaloneWindows64
          - name: Linux
            platform: StandaloneLinux64
          - name: MacOS
            platform: StandaloneOSX
          - name: WebGL
            platform: WebGL
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v3
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - name: Restore Library cache
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-build-${{ matrix.targetPlatform.platform }}
          restore-keys: |
            Library-build-
            Library-

      - uses: game-ci/unity-builder@v4
        with:
          targetPlatform: ${{ matrix.targetPlatform.platform }}
          buildName: UnityTemplate

      - uses: actions/upload-artifact@v3
        with:
          name: UnityTemplate-${{ matrix.targetPlatform.name }}
          path: build/${{ matrix.targetPlatform.platform }}
